 local menud51ff67768edbb1ac85d6f654b29a1f1 = {
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
 }

 local menu63909e8219db0bcede147cb7926a07fa = {
     {"Dokumentenbetrachter", "evince "},
     {"Kalender", "io.elementary.calendar "},
     {"Kalender", "gnome-calendar"},
     {"LibreOffice", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Wörterbuch", "xfce4-dict", "/usr/share//icons/hicolor/16x16/apps/org.xfce.Dictionary.png" },
 }

 local menu9356bc29cbd145b1b330eaeb7614fd1e = {
     {"Boxen", "gnome-boxes "},
     {"CMake", "cmake-gui ", "/usr/share//icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Code", "io.elementary.code ", "/usr/share//icons/hicolor/16x16/apps/io.elementary.code.svg" },
     {"Cuttlefish", "cuttlefish"},
     {"GdaBrowser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Globaler Plasma-Designexplorer", "lookandfeelexplorer"},
     {"Plasma-Datenquellen-Betrachter", "plasmaengineexplorer"},
     {"Plasma-Designexplorer", "plasmathemeexplorer"},
     {"Qt Assistant", "assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share//icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share//icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"UserFeedback-Konsole", "UserFeedbackConsole"},
 }

 local menue64b29f9c504872c202fabd746ddbf8a = {
     {"Bildbetrachter", "eog "},
     {"Deepin Bildbetrachter", "deepin-image-viewer --new-window "},
     {"Dokument-Scanner", "simple-scan"},
     {"Dokumentenbetrachter", "evince "},
     {"Gpick", "gpick", "/usr/share//icons/hicolor/48x48/apps/gpick.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Photos", "io.elementary.photos "},
     {"Ristretto-Bildbetrachter", "ristretto ", "/usr/share//icons/hicolor/16x16/apps/ristretto.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH-Server-Browser", "/usr/bin/bssh"},
     {"Avahi VNC-Server-Browser", "/usr/bin/bvnc"},
     {"Ein verbundenes Gerät mit KDE Connect öffnen", "kdeconnect-handler --open "},
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect-SMS", "kdeconnect-sms"},
     {"KDE-Connect-Anzeige", "kdeconnect-indicator"},
     {"Web", "epiphany "},
 }

 local menuaf8e527fa7389d550718563dbd09e634 = {
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Boxen", "gnome-boxes "},
     {"Clock", "/usr/bin/ukui-clock"},
     {"Dateien", "io.elementary.files "},
     {"Deepin System Monitor", "deepin-system-monitor"},
     {"Discover", "plasma-discover ", "/usr/share//icons/hicolor/16x16/apps/plasmadiscover.png" },
     {"Dolphin", "dolphin "},
     {"Farbprofilbetrachter", "gcm-viewer", "/usr/share//icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Feedback", "/usr/bin/ukui-feedback"},
     {"Festplattenbelegungsanalyse", "baobab "},
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard "},
     {"Konsole", "konsole"},
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Massenumbenennen", "thunar --bulk-rename ", "/usr/share//icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Notebook", "/usr/bin/ukui-notebook"},
     {"PCManFM Dateimanager", "pcmanfm "},
     {"Parental Controls", "malcontent-control"},
     {"Protokolle", "gnome-logs"},
     {"Sensorbetrachter", "xfce4-sensors", "/usr/share//icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"Software", "gnome-software "},
     {"System installieren", "pkexec /usr/bin/calamares"},
     {"Systemeinstellungen", "io.elementary.switchboard "},
     {"Systemüberwachung", "gnome-system-monitor"},
     {"Taskmanager", "xfce4-taskmanager", "/usr/share//icons/hicolor/16x16/apps/org.xfce.taskmanager.png" },
     {"Terminal", "gnome-terminal"},
     {"Terminal", "io.elementary.terminal"},
     {"Termite", "termite"},
     {"Thunar-Dateiverwaltung", "thunar ", "/usr/share//icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Tilix", "tilix"},
     {"Tint2", "tint2"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce-Terminal", "xfce4-terminal", "/usr/share//icons/hicolor/16x16/apps/org.xfce.terminal.png" },
     {"dconf-Editor", "dconf-editor", "/usr/share//icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"kitty", "kitty", "/usr/share//icons/hicolor/256x256/apps/kitty.png" },
     {"urxvt", "urxvt"},
     {"urxvt (client)", "urxvtc"},
     {"urxvt (tabbed)", "urxvt-tabbed"},
 }

 local menu832f9901685a4e0cfef90f462339cb43 = {
     {"Cheese", "cheese"},
     {"DeaDBeeF", "deadbeef ", "/usr/share//icons/hicolor/16x16/apps/deadbeef.png" },
     {"Musik", "io.elementary.music ", "/usr/share//icons/hicolor/16x16/apps/multimedia-audio-player.svg" },
     {"Musik", "gnome-music"},
     {"Parole-Medienspieler", "parole ", "/usr/share//icons/hicolor/16x16/apps/org.xfce.parole.png" },
     {"PulseAudio-Lautstärkeregler", "pavucontrol"},
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share//icons/hicolor/16x16/apps/qvidcap.png" },
     {"Videos", "io.elementary.videos "},
     {"Videos", "totem "},
     {"Volume Icon", "volumeicon"},
     {"Xfburn", "xfburn"},
 }

 local menuf022205808b7868110a5722844a76ab7 = {
     {"Anwendungsfinder", "xfce4-appfinder", "/usr/share//icons/hicolor/16x16/apps/org.xfce.appfinder.png" },
     {"Archivverwaltung", "file-roller "},
     {"Bildschirmfoto", "io.elementary.screenshot-tool", "/usr/share//icons/hicolor/32x32/apps/accessories-screenshot.svg" },
     {"Bildschirmfoto", "gnome-screenshot --interactive"},
     {"Bildschirmfoto", "xfce4-screenshooter", "/usr/share//icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
     {"Dateien", "nautilus --new-window "},
     {"Deepin Dateimanager", "/usr/bin/dde-file-manager -n "},
     {"Deepin Kalender", "dde-calendar"},
     {"Hauptmenü", "alacarte", "/usr/share//icons/hicolor/16x16/apps/alacarte.png" },
     {"Karten", "gapplication launch org.gnome.Maps "},
     {"Klipper", "klipper"},
     {"Kvantum Manager", "kvantummanager"},
     {"Laufwerke", "gnome-disks"},
     {"Marker", "marker "},
     {"Mousepad", "mousepad ", "/usr/share//icons/hicolor/16x16/apps/org.xfce.mousepad.png" },
     {"PCManFM-Qt", "pcmanfm-qt "},
     {"Plank", "plank", "/usr/share//icons/hicolor/16x16/apps/plank.svg" },
     {"Rechner", "io.elementary.calculator "},
     {"Schriften", "gnome-font-viewer "},
     {"Taschenrechner", "gnome-calculator"},
     {"Texteditor", "gedit "},
     {"Uhren", "gnome-clocks"},
     {"Ulauncher", "env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window", "/usr/share//icons/hicolor/48x48/apps/ulauncher.svg" },
     {"Vim", "xterm -e vim ", "/usr/share//icons/hicolor/48x48/apps/gvim.png" },
     {"Wetter", "gapplication launch org.gnome.Weather"},
     {"Xfburn", "xfburn"},
     {"Zeichen", "/usr/bin/gnome-characters"},
     {"compton", "compton", "/usr/share//icons/hicolor/48x48/apps/compton.png" },
     {"indicator-china-weather", "/usr/bin/indicator-china-weather ", "/usr/share/pixmaps/indicator-china-weather.png" },
     {"nitrogen", "nitrogen", "/usr/share//icons/hicolor/16x16/apps/nitrogen.png" },
     {"picom", "picom"},
 }

xdgmenu = {
    {"Bildung", menud51ff67768edbb1ac85d6f654b29a1f1},
    {"Büro", menu63909e8219db0bcede147cb7926a07fa},
    {"Entwicklung", menu9356bc29cbd145b1b330eaeb7614fd1e},
    {"Grafik", menue64b29f9c504872c202fabd746ddbf8a},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Systemwerkzeuge", menuaf8e527fa7389d550718563dbd09e634},
    {"Unterhaltungsmedien", menu832f9901685a4e0cfef90f462339cb43},
    {"Zubehör", menuf022205808b7868110a5722844a76ab7},
}

